spring:
    datasource:
        url: jdbc:sqlserver://jbhogapurapudb.database.windows.net:1433;database=jbhogapurapudb;user=jbhogapurapu@jbhogapurapudb;password={your_password_here};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
        username: jbhogapurapu
        password: Jagadeesh@07
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.SQLServer2012Dialect
server:
    port: 8080
